---
resources:
  - name: every-3-hours
    type: time
    source:
      interval: 3h

  - name: osbook
    type: git
    source:
      uri: git@github.com:openstax/osbooks-college-algebra-bundle.git
      branch: staging
      private_key: ((github-private-key))

jobs:
  - name: sync-staging-branch
    public: true
    plan:
    - get: every-3-hours
      trigger: true
    - get: osbook
    - task: sync content
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            username: ((docker-username))
            password: ((docker-password))
            repository: bn16/osbook-synchronizer
        inputs:
          - name: osbook
        outputs:
          - name: updated-osbook
        run:
          path: /bin/bash
          args:
            - '-cxe'
            - |-

              git clone osbook updated-osbook

              cd updated-osbook
              export CODE_DIR="/code/scripts"
              bash $CODE_DIR/sync.sh

              git config --global user.email "bigbird@sesamestreet.com"
              git config --global user.name "Big Bird"

              git add .
              git commit -m "sync with archive staging"

    - put: osbook
      params: {repository: updated-osbook}
