---
var_sources:
  - name: github
    type: dummy
    config:
      vars:
        username:
        token:
        email:
        organization:
        openstax:
          username:
          token:

docker-credentials: &docker-credentials
  username: ((ce-dockerhub-id))
  password: ((ce-dockerhub-token))

status-notifications: &status-notifications
  on_success:
    put: notify
    params:
      alert_type: success
  on_failure:
    put: notify
    params:
      alert_type: failed

resource_types:
  - name: queue-checker
    type: registry-image
    source:
      repository: golfpapagolf/queue-checker
  - name: slack-notifier
    type: registry-image
    # Switch back to mockersf/concourse-slack-notifier once
    # https://github.com/mockersf/concourse-slack-notifier/pull/86 is merged
    source:
      repository: aoldershaw/concourse-slack-notifier

resources:
  - name: queue
    type: queue-checker
    check_every: 1m
    source:
      uri: https://gist.githubusercontent.com/optimussam/946fc5a064137717aef2fb76ac3565d1/raw/0f4f49ec5d76593b6d61c25bca2cbf63002aa91b/openstax_derived_books.json

  - name: content-synchronizer
    type: git
    source:
      uri: https://github.com/openstax/content-synchronizer
      branch: main

  - name: notify
    type: slack-notifier
    icon: slack
    source:
      url: ((slack-webhook-cestream))

jobs:
  - name: sync-a-book
    <<: *status-notifications
    public: true
    max_in_flight: 5
    plan:
      - in_parallel:
        - get: queue
          trigger: true
          version: every
        - get: content-synchronizer
      - task: sync-content
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: samuelklutse/openstax-cnx-migration
              tag: latest
              <<: *docker-credentials

          inputs:
            - name: queue
            - name: content-synchronizer
          run:
            path: /bin/bash
            args:
              - -c
              - |
                set -x
                item="$(cat queue/item)"
                [[ ! "$item" ]] && exit 1
                collection_id=`echo $item | jq -r '.collection_id'`
                slug=`echo $item | jq -r '.slug'`
                name=`echo $item | jq -r '.name'`
                migrate=`echo $item | jq -r '.migrate'`
                parent_repository_name=`echo $item | jq -r '.parent_repository_name'`
                repository_name=`echo $item | jq -r '.repository_name'`
                if [ "$migrate" = false ] ; then 
                  echo "$slug cannot be migrated"
                  exit 1
                fi
                ROOT_DIR=`pwd`
                mkdir -p tmp
                mkdir -p /root/.ssh
                cd tmp
                CODE_DIR=$ROOT_DIR/content-synchronizer/resource-synchronizer SERVER=cnx.org ../content-synchronizer/resource-synchronizer/sync.sh -u ((github:username)) -p ((github:token)) -e ((github:email)) -r $repository_name -c -k ((github:openstax.username)) -l ((github:openstax.token)) -o $parent_repository_name -q ((github:organization))
                exit 0