name: Build and Push Image
on:
  # Remove pull request after testing has been done on PR
  pull_request:
  push:
    branches:
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          cd ./resource-synchronizer
          docker build . --tag image --file Dockerfile
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}