---
name: tests
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0' # weekly
jobs:
  tests:
    timeout-minutes: 30
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: ['3.6']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Test
        run: |
          pip install -r resource-synchronizer/requirements.txt
          pip install pytest pytest-mock requests-mock
          cp resource-synchronizer/poet.json poet.json
          pytest resource-synchronizer/test_sync_scripts.py
          pytest resource-trigger/test_sync_trigger.py
